# Generated by Django 3.2.6 on 2021-08-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True)),
                ('endereco', models.CharField(db_index=True, max_length=100)),
                ('telefone', models.IntegerField(db_index=True, max_length=11)),
                ('cnpj', models.IntegerField(db_index=True, max_length=14)),
            ],
            options={
                'db_table': 'fornecedores',
                'ordering': ('nome',),
            },
        ),
    ]
