# Generated by Django 3.2.6 on 2021-08-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.CharField(max_length=150)),
                ('imagem', models.CharField(blank=True, max_length=100)),
                ('qtd_estoque', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('disponivel', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
