# Generated by Django 3.2.6 on 2021-09-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='qtd_estoque',
            new_name='qtd',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto2',
        ),
    ]
